# Generated by Django 5.1.6 on 2025-02-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier'), ('warehouse', 'Warehouse Staff')], default='manager', max_length=10),
        ),
    ]
